// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:my_flash_cards/models/deck.dart';
import 'package:my_flash_cards/models/flashcard.dart';
import 'package:my_flash_cards/models/study_session.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DeckAdapter());
    registerAdapter(FlashcardAdapter());
    registerAdapter(StudySessionAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(DeckAdapter());
    registerAdapter(FlashcardAdapter());
    registerAdapter(StudySessionAdapter());
  }
}
