import 'dart:io';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:uuid/uuid.dart';
import '../../blocs/deck/deck_bloc.dart';
import '../../blocs/deck/deck_event.dart';
import '../../blocs/flashcard/flashcard_bloc.dart';
import '../../blocs/flashcard/flashcard_event.dart';
import '../../models/deck.dart';
import '../../models/flashcard.dart';
import '../../services/ai_deck_service.dart';

// ---------------------------------------------------------------------------
// API key is loaded from --dart-define=GEMINI_API_KEY=your_key at run time.
// Get a free key at: https://aistudio.google.com/app/apikey
//
// When ready to release publicly, see:
//   lib/services/firebase_function_generator_service.dart
// for the one-line swap to use a Firebase Cloud Function instead.
// ---------------------------------------------------------------------------
const _kGeminiApiKey = String.fromEnvironment(
  'GEMINI_API_KEY',
  defaultValue: '',
);

class AiGenerateScreen extends StatefulWidget {
  const AiGenerateScreen({super.key});

  @override
  State<AiGenerateScreen> createState() => _AiGenerateScreenState();
}

class _AiGenerateScreenState extends State<AiGenerateScreen> {
  // Typed as the abstract interface — swap to FirebaseFunctionGeneratorService
  // when upgrading to Blaze plan. See firebase_function_generator_service.dart.
  final CardGeneratorService _service = GeminiDirectService(_kGeminiApiKey);
  final _topicController = TextEditingController();
  final _formKey = GlobalKey<FormState>();

  bool _loading = false;
  String? _fileName;
  String? _fileText;

  // Once generated, cards are shown here for preview/editing
  List<_EditableCard> _suggestions = [];

  @override
  void dispose() {
    _topicController.dispose();
    super.dispose();
  }

  // ── File picker ──────────────────────────────────────────────────────────

  Future<void> _pickFile() async {
    final result = await FilePicker.platform.pickFiles(
      type: FileType.custom,
      allowedExtensions: ['txt', 'md', 'csv'],
      withData: true,
    );
    if (result == null || result.files.isEmpty) return;
    final file = result.files.first;

    String text;
    if (file.bytes != null) {
      text = String.fromCharCodes(file.bytes!);
    } else if (file.path != null) {
      text = await File(file.path!).readAsString();
    } else {
      return;
    }

    setState(() {
      _fileName = file.name;
      _fileText = text;
      _topicController.clear();
    });
  }

  // ── Generation ───────────────────────────────────────────────────────────

  Future<void> _generate() async {
    if (_kGeminiApiKey.isEmpty) {
      _snack(
        'No Gemini API key configured.\n'
        'Run: flutter run --dart-define=GEMINI_API_KEY=your_key',
        isError: true,
      );
      return;
    }
    if (_fileText == null && !_formKey.currentState!.validate()) return;

    setState(() {
      _loading = true;
      _suggestions = [];
    });
    try {
      final cards = _fileText != null
          ? await _service.generateFromText(_fileText!)
          : await _service.generateFromTopic(_topicController.text.trim());

      setState(() {
        _suggestions =
            cards.map((c) => _EditableCard(front: c.front, back: c.back)).toList();
      });
    } catch (e) {
      _snack(e.toString(), isError: true);
    } finally {
      if (mounted) setState(() => _loading = false);
    }
  }

  // ── Save ─────────────────────────────────────────────────────────────────

  Future<void> _saveDeck() async {
    final cards = _suggestions.where((c) => !c.removed).toList();
    if (cards.isEmpty) {
      _snack('Remove all cards then there\'s nothing to save.', isError: true);
      return;
    }

    final topic = _fileText != null
        ? (_fileName ?? 'Uploaded Document')
        : _topicController.text.trim();

    final deckName = _toTitleCase(topic);
    final now = DateTime.now();
    final deckId = const Uuid().v4();

    final deck = Deck(
      id: deckId,
      name: deckName,
      description: 'Generated by AI from: $topic',
      createdAt: now,
      updatedAt: now,
    );

    if (!mounted) return;
    context.read<DeckBloc>().add(AddDeck(deck));

    for (final card in cards) {
      final flashcard = Flashcard(
        id: const Uuid().v4(),
        deckId: deckId,
        front: card.front,
        back: card.back,
        createdAt: now,
        updatedAt: now,
      );
      context.read<FlashcardBloc>().add(AddFlashcard(flashcard));
    }

    if (mounted) {
      _snack('Deck "$deckName" saved with ${cards.length} cards ✓');
      Navigator.pop(context);
    }
  }

  // ── Helpers ──────────────────────────────────────────────────────────────

  String _toTitleCase(String s) => s
      .split(' ')
      .map((w) => w.isEmpty ? w : '${w[0].toUpperCase()}${w.substring(1)}')
      .join(' ');

  void _snack(String msg, {bool isError = false}) {
    if (!mounted) return;
    ScaffoldMessenger.of(context).showSnackBar(SnackBar(
      content: Text(msg),
      behavior: SnackBarBehavior.floating,
      backgroundColor:
          isError ? Theme.of(context).colorScheme.error : null,
    ));
  }

  // ── Build ────────────────────────────────────────────────────────────────

  @override
  Widget build(BuildContext context) {
    final cs = Theme.of(context).colorScheme;
    final hasSuggestions = _suggestions.isNotEmpty;
    final visibleCount = _suggestions.where((c) => !c.removed).length;

    return Scaffold(
      appBar: AppBar(
        title: const Text('Generate with AI'),
        actions: [
          if (hasSuggestions)
            FilledButton.icon(
              onPressed: _loading ? null : _saveDeck,
              icon: const Icon(Icons.save_outlined),
              label: Text('Save ($visibleCount)'),
            ),
          const SizedBox(width: 8),
        ],
      ),
      body: Stack(
        children: [
          CustomScrollView(
            slivers: [
              SliverToBoxAdapter(
                child: Padding(
                  padding: const EdgeInsets.all(20),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    children: [
                      // ── Topic input ──────────────────────────────────────
                      Text(
                        'Describe your topic',
                        style: Theme.of(context)
                            .textTheme
                            .titleMedium
                            ?.copyWith(fontWeight: FontWeight.w600),
                      ),
                      const SizedBox(height: 8),
                      Form(
                        key: _formKey,
                        child: TextFormField(
                          controller: _topicController,
                          enabled: _fileText == null && !_loading,
                          decoration: InputDecoration(
                            hintText:
                                'e.g. CVC words for a beginning reader',
                            prefixIcon: const Icon(Icons.lightbulb_outline),
                            suffixIcon: _topicController.text.isNotEmpty
                                ? IconButton(
                                    icon: const Icon(Icons.clear),
                                    onPressed: () => setState(
                                        () => _topicController.clear()),
                                  )
                                : null,
                          ),
                          maxLines: 2,
                          minLines: 1,
                          textCapitalization: TextCapitalization.sentences,
                          onChanged: (_) => setState(() {}),
                          validator: (v) =>
                              (v == null || v.trim().isEmpty)
                                  ? 'Enter a topic or upload a file'
                                  : null,
                        ),
                      ),

                      // ── OR divider ───────────────────────────────────────
                      Padding(
                        padding: const EdgeInsets.symmetric(vertical: 16),
                        child: Row(
                          children: [
                            const Expanded(child: Divider()),
                            Padding(
                              padding:
                                  const EdgeInsets.symmetric(horizontal: 12),
                              child: Text('OR',
                                  style:
                                      TextStyle(color: cs.outline)),
                            ),
                            const Expanded(child: Divider()),
                          ],
                        ),
                      ),

                      // ── File upload ──────────────────────────────────────
                      OutlinedButton.icon(
                        onPressed: _loading ? null : _pickFile,
                        icon: const Icon(Icons.upload_file_outlined),
                        label: Text(_fileName != null
                            ? _fileName!
                            : 'Upload .txt or .md file'),
                      ),
                      if (_fileName != null) ...[
                        const SizedBox(height: 6),
                        Row(
                          children: [
                            Icon(Icons.check_circle_outline,
                                size: 14, color: cs.primary),
                            const SizedBox(width: 4),
                            Expanded(
                              child: Text(
                                '$_fileName loaded — ${_fileText!.length} characters',
                                style: TextStyle(
                                    fontSize: 12, color: cs.outline),
                                overflow: TextOverflow.ellipsis,
                              ),
                            ),
                            IconButton(
                              icon: const Icon(Icons.close, size: 16),
                              onPressed: () => setState(() {
                                _fileName = null;
                                _fileText = null;
                              }),
                            ),
                          ],
                        ),
                      ],

                      const SizedBox(height: 20),

                      // ── Generate / Regenerate button ─────────────────────
                      FilledButton.icon(
                        onPressed: _loading ? null : _generate,
                        icon: const Icon(Icons.auto_awesome),
                        label: Text(hasSuggestions
                            ? 'Regenerate'
                            : 'Generate Cards'),
                      ),

                      if (hasSuggestions) ...[
                        const SizedBox(height: 24),
                        Row(
                          children: [
                            Text(
                              'Preview — tap ✕ to remove a card',
                              style: TextStyle(
                                  fontSize: 12, color: cs.outline),
                            ),
                            const Spacer(),
                            Text(
                              '$visibleCount cards',
                              style: TextStyle(
                                  fontSize: 12,
                                  color: cs.primary,
                                  fontWeight: FontWeight.w600),
                            ),
                          ],
                        ),
                        const SizedBox(height: 8),
                      ],
                    ],
                  ),
                ),
              ),

              // ── Card preview list ────────────────────────────────────────
              if (hasSuggestions)
                SliverPadding(
                  padding: const EdgeInsets.fromLTRB(20, 0, 20, 120),
                  sliver: SliverList.builder(
                    itemCount: _suggestions.length,
                    itemBuilder: (context, i) {
                      final card = _suggestions[i];
                      if (card.removed) return const SizedBox.shrink();
                      return _PreviewCard(
                        card: card,
                        index: i + 1,
                        onRemove: () =>
                            setState(() => _suggestions[i].removed = true),
                        onEditFront: (v) => _suggestions[i].front = v,
                        onEditBack: (v) => _suggestions[i].back = v,
                      );
                    },
                  ),
                ),
            ],
          ),

          if (_loading)
            const Positioned.fill(
              child: ColoredBox(
                color: Colors.black26,
                child: Center(
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      CircularProgressIndicator(),
                      SizedBox(height: 16),
                      Text('Generating cards…',
                          style: TextStyle(
                              color: Colors.white,
                              fontWeight: FontWeight.w600)),
                    ],
                  ),
                ),
              ),
            ),
        ],
      ),
    );
  }
}

// ── Mutable card model for preview ──────────────────────────────────────────

class _EditableCard {
  String front;
  String back;
  // ignore: avoid_positional_boolean_parameters
  bool removed = false;
  _EditableCard({required this.front, required this.back});
}

// ── Preview card widget ──────────────────────────────────────────────────────

class _PreviewCard extends StatelessWidget {
  final _EditableCard card;
  final int index;
  final VoidCallback onRemove;
  final ValueChanged<String> onEditFront;
  final ValueChanged<String> onEditBack;

  const _PreviewCard({
    required this.card,
    required this.index,
    required this.onRemove,
    required this.onEditFront,
    required this.onEditBack,
  });

  @override
  Widget build(BuildContext context) {
    final cs = Theme.of(context).colorScheme;
    return Card(
      margin: const EdgeInsets.only(bottom: 10),
      child: Padding(
        padding: const EdgeInsets.fromLTRB(14, 10, 8, 12),
        child: Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Card number badge
            Padding(
              padding: const EdgeInsets.only(top: 4, right: 10),
              child: CircleAvatar(
                radius: 12,
                backgroundColor: cs.primaryContainer,
                child: Text('$index',
                    style: TextStyle(
                        fontSize: 10,
                        color: cs.onPrimaryContainer,
                        fontWeight: FontWeight.bold)),
              ),
            ),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  _InlineEditField(
                    label: 'Front',
                    value: card.front,
                    color: cs.primary,
                    onChanged: onEditFront,
                  ),
                  const SizedBox(height: 6),
                  _InlineEditField(
                    label: 'Back',
                    value: card.back,
                    color: cs.secondary,
                    onChanged: onEditBack,
                  ),
                ],
              ),
            ),
            IconButton(
              icon: Icon(Icons.close, size: 18, color: cs.outline),
              onPressed: onRemove,
              tooltip: 'Remove card',
            ),
          ],
        ),
      ),
    );
  }
}

class _InlineEditField extends StatefulWidget {
  final String label;
  final String value;
  final Color color;
  final ValueChanged<String> onChanged;
  const _InlineEditField({
    required this.label,
    required this.value,
    required this.color,
    required this.onChanged,
  });

  @override
  State<_InlineEditField> createState() => _InlineEditFieldState();
}

class _InlineEditFieldState extends State<_InlineEditField> {
  late final TextEditingController _ctrl;

  @override
  void initState() {
    super.initState();
    _ctrl = TextEditingController(text: widget.value);
  }

  @override
  void dispose() {
    _ctrl.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return TextFormField(
      controller: _ctrl,
      onChanged: widget.onChanged,
      style: const TextStyle(fontSize: 13),
      decoration: InputDecoration(
        labelText: widget.label,
        labelStyle: TextStyle(
            fontSize: 11,
            color: widget.color,
            fontWeight: FontWeight.w600),
        isDense: true,
        contentPadding:
            const EdgeInsets.symmetric(vertical: 6, horizontal: 8),
      ),
      minLines: 1,
      maxLines: 3,
    );
  }
}
